version: '3.8'
services:
  azure-function:
    build:
      context: .
      dockerfile: ./dotnet-groomer/Dockerfile
    ports:
      - "8080:80"
    environment:
      AzureWebJobsScriptRoot: /home/site/wwwroot
      AzureFunctionsJobHost__Logging__Console__IsEnabled: true
      AzureFunctionsJobHost__extensions__cors__allowedOrigins: "http://localhost:3000"
      AzureFunctionsJobHost__extensions__cors__supportCredentials: false
    env_file:
      - ./docker.env

  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: dotnet_groomer
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql-db
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      - mysql-db

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  mysql-data:
  caddy_data:
  caddy_config: